type Vraag {
  naam: String!
  email: String!
  vraag: String!
  titel: String
  antwoord: String
  status: String!
  images: [Image]
  datum: Time!
  publicatieDatum: Time
}

type Image @embedded {
  id: String
  url: String
}

type Query {
  alleVragen: [Vraag!]! @resolver(name: "sortByDate", paginated: true)
  alleGepubliceerdeVragen(status: String!): [Vraag!]!
    @resolver(name: "sortByPublicationDate", paginated: true)
}
